# Modelo IQR

In [81]:
import numpy as np
import pandas as pd

## Dataset Wind

In [82]:
# Replace 'your_file.npy' with the path to your .npy file
file_path = '../resultados_grid_search/Wind/Wind_OOB_plus_IQR.npy'
data_wind = np.load(file_path)

# Define column names
columns = ['n_estimators', 'group_size', 'max_depth', 'MSE']

# Create a DataFrame
df_wind = pd.DataFrame(data_wind, columns=columns)

# Display the DataFrame
df_wind

     n_estimators  group_size  max_depth        MSE
0           150.0        15.0       29.0  18.849424
1           500.0        25.0       48.0  18.708950
2           200.0        25.0       43.0  18.729967
3           400.0         8.0       13.0  18.758089
4           220.0        10.0       20.0  18.794184
..            ...         ...        ...        ...
995         210.0        35.0       50.0  18.770443
996         240.0         6.0       25.0  18.692616
997         350.0         7.0       11.0  18.698097
998         550.0        10.0       11.0  18.605762
999          70.0        10.0       25.0  18.736065

[1000 rows x 4 columns]

In [83]:
sorted_df_wind = df_wind.sort_values(by='MSE', ascending=True)
sorted_df_wind['Rank'] = range(1, len(sorted_df_wind) + 1)

top_50_wind = sorted_df_wind[:50]
top_50_wind

     n_estimators  group_size  max_depth        MSE  Rank
548          90.0         3.0       19.0  18.285275     1
313          60.0         3.0       12.0  18.311020     2
56           90.0         3.0       31.0  18.361193     3
102          90.0         3.0       32.0  18.361193     4
882          90.0         3.0       44.0  18.361193     5
370         180.0         4.0       12.0  18.367756     6
551         150.0         3.0       12.0  18.382172     7
461         600.0         3.0       15.0  18.382862     8
701          80.0         5.0       12.0  18.386692     9
68          450.0         3.0       11.0  18.404598    10
303         180.0         3.0       14.0  18.417501    11
703         600.0         3.0       16.0  18.424500    12
349         270.0         3.0       17.0  18.427896    13
670          80.0        10.0       12.0  18.432264    14
847         210.0         3.0       19.0  18.438560    15
894         600.0         3.0       39.0  18.439352    16
545         240.0         3.0       14.0  18.440279    17
28           90.0        10.0       12.0  18.440542    18
54          240.0         3.0       19.0  18.443758    19
175         450.0         3.0       18.0  18.453447    20
226         270.0         3.0       25.0  18.455395    21
45          600.0         3.0       24.0  18.460209    22
811         300.0         3.0       46.0  18.470257    23
335         300.0         3.0       44.0  18.470257    24
971         300.0         3.0       34.0  18.470257    25
883         300.0         3.0       39.0  18.470257    26
229         300.0         3.0       47.0  18.470257    27
409         900.0         3.0       10.0  18.475918    28
850         270.0         3.0       23.0  18.476290    29
525          90.0         3.0       23.0  18.478868    30
600         750.0         3.0       10.0  18.479589    31
162         180.0         5.0       12.0  18.482924    32
18          120.0         3.0       44.0  18.483063    33
927         120.0         3.0       35.0  18.483063    34
379         120.0         3.0       31.0  18.483063    35
232         120.0         3.0       37.0  18.483063    36
211         180.0         3.0       22.0  18.483461    37
264         120.0         3.0       28.0  18.486462    38
446         900.0         3.0       19.0  18.487654    39
372         700.0         4.0       12.0  18.487755    40
855         500.0         4.0       11.0  18.491297    41
645         750.0         3.0       39.0  18.492159    42
775         900.0         3.0       36.0  18.493597    43
906         900.0         3.0       33.0  18.493597    44
783         900.0         3.0       41.0  18.493597    45
736        1500.0         3.0       10.0  18.494064    46
591         900.0         3.0       28.0  18.494242    47
220         180.0         3.0       49.0  18.497604    48
655         180.0         3.0       31.0  18.497604    49
676         180.0         3.0       42.0  18.497604    50

## Dataset Carbon Emission

In [84]:
file_path = '../resultados_grid_search/Carbon_Emission/Carbon_Emission_OOB_plus_IQR.npy'
data_carbon = np.load(file_path)

# Define column names
columns = ['n_estimators', 'group_size', 'max_depth', 'MSE']

# Create a DataFrame
df_carbon = pd.DataFrame(data_carbon, columns=columns)

# Display the DataFrame
df_carbon

     n_estimators  group_size  max_depth           MSE
0           750.0        15.0       23.0  266643.28125
1           120.0         3.0       29.0  264514.18750
2            90.0         3.0       20.0  262739.87500
3           110.0         5.0       20.0  263694.09375
4          1000.0        20.0       10.0  278887.25000
..            ...         ...        ...           ...
995         450.0        50.0       39.0  266421.78125
996        1250.0        10.0       20.0  266841.65625
997         850.0        50.0       24.0  266276.84375
998          70.0        10.0       25.0  268862.15625
999         150.0        25.0       14.0  265901.00000

[1000 rows x 4 columns]

In [85]:
sorted_df_carbon = df_carbon.sort_values(by='MSE', ascending=True)
sorted_df_carbon['Rank'] = range(1, len(sorted_df_carbon) + 1)

top_50_carbon = sorted_df_carbon[:50]
top_50_carbon

     n_estimators  group_size  max_depth            MSE  Rank
141         160.0         5.0       17.0  261329.156250     1
236         160.0         4.0       17.0  261565.015625     2
136         180.0         3.0       21.0  261683.640625     3
438         180.0         3.0       18.0  261704.500000     4
780         200.0        50.0       17.0  261848.046875     5
987         150.0        50.0       20.0  262000.312500     6
781         150.0         3.0       39.0  262008.078125     7
833         150.0         3.0       34.0  262008.078125     8
572         150.0         3.0       36.0  262008.078125     9
621         150.0         3.0       38.0  262008.078125    10
125         180.0         3.0       34.0  262023.984375    11
688         180.0         3.0       28.0  262023.984375    12
58          180.0         3.0       47.0  262023.984375    13
765         180.0         3.0       42.0  262023.984375    14
561         180.0         4.0       17.0  262109.625000    15
619         180.0         4.0       20.0  262299.718750    16
334         180.0        30.0       16.0  262364.687500    17
681         350.0         7.0       20.0  262503.937500    18
128         180.0         6.0       20.0  262618.437500    19
2            90.0         3.0       20.0  262739.875000    20
155         270.0        45.0       20.0  262853.750000    21
895         180.0        20.0       16.0  262867.656250    22
11          180.0        45.0       28.0  262969.312500    23
924         180.0        30.0       19.0  262995.593750    24
686         270.0         3.0       14.0  263003.375000    25
812         240.0         3.0       38.0  263023.187500    26
866         240.0         3.0       36.0  263023.187500    27
959         240.0         3.0       32.0  263023.187500    28
29          240.0         3.0       28.0  263023.187500    29
770         250.0        10.0       20.0  263032.187500    30
313         210.0        10.0       19.0  263231.531250    31
606         210.0         3.0       41.0  263241.062500    32
920         210.0         3.0       42.0  263241.062500    33
5           260.0         4.0       20.0  263246.625000    34
795         150.0        50.0       19.0  263314.406250    35
259         400.0         4.0       20.0  263324.250000    36
953         180.0        20.0       44.0  263377.562500    37
117         180.0        20.0       33.0  263377.562500    38
626         180.0        20.0       46.0  263377.562500    39
914         180.0        20.0       28.0  263377.562500    40
167         150.0         3.0       15.0  263461.625000    41
531         270.0         3.0       32.0  263470.468750    42
70          270.0         3.0       47.0  263470.468750    43
733         160.0        40.0       16.0  263484.687500    44
172         600.0         3.0       20.0  263484.843750    45
317         160.0        20.0       39.0  263530.937500    46
970         160.0        20.0       37.0  263530.937500    47
893         170.0        10.0       18.0  263566.968750    48
699         180.0        20.0       18.0  263683.437500    49
325         270.0        30.0       19.0  263693.343750    50

## House 8L

In [86]:
file_path = '../resultados_grid_search/House_8L/House_8L_OOB_plus_IQR.npy'
data_house_8L = np.load(file_path)

# Define column names
columns = ['n_estimators', 'group_size', 'max_depth', 'MSE']

# Create a DataFrame
df_house_8L = pd.DataFrame(data_house_8L, columns=columns)

# Display the DataFrame
df_house_8L

     n_estimators  group_size  max_depth          MSE
0           300.0        25.0       26.0  975657088.0
1           120.0        15.0       32.0  969961600.0
2           500.0        20.0       37.0  965989696.0
3           900.0         4.0       18.0  960692800.0
4           250.0        10.0       27.0  956645824.0
..            ...         ...        ...          ...
995        1000.0        25.0       12.0  986872512.0
996         280.0         4.0       17.0  958064576.0
997         270.0         6.0       10.0  993350528.0
998         500.0        50.0       29.0  970197312.0
999          90.0        15.0       20.0  977531072.0

[1000 rows x 4 columns]

In [87]:
sorted_df_house_8L = df_house_8L.sort_values(by='MSE', ascending=True)
sorted_df_house_8L['Rank'] = range(1, len(sorted_df_house_8L) + 1)

top_50_house_8L = sorted_df_house_8L[:50]
top_50_house_8L

     n_estimators  group_size  max_depth          MSE  Rank
168         700.0         7.0       22.0  951852288.0     1
708         750.0         3.0       34.0  952757888.0     2
301        1500.0         3.0       27.0  952838016.0     3
229         600.0         3.0       22.0  952943744.0     4
713         180.0         4.0       42.0  952956800.0     5
296         180.0         4.0       38.0  952956800.0     6
720         180.0         4.0       40.0  952956800.0     7
638         750.0         3.0       41.0  953036352.0     8
612         180.0         3.0       43.0  953402304.0     9
14          750.0         3.0       30.0  953422784.0    10
258         900.0         3.0       34.0  953494976.0    11
35          150.0         3.0       38.0  953692672.0    12
65          150.0         3.0       36.0  953692672.0    13
533         150.0         3.0       45.0  953692672.0    14
962         150.0         3.0       35.0  953692672.0    15
76          150.0         3.0       34.0  953692672.0    16
735         600.0         3.0       31.0  953704704.0    17
625         600.0         3.0       21.0  953724992.0    18
156         450.0         3.0       38.0  953861568.0    19
53          180.0         3.0       23.0  954156992.0    20
153         270.0         3.0       34.0  954292800.0    21
950         270.0         3.0       38.0  954392320.0    22
45          300.0         3.0       23.0  954425984.0    23
77          300.0         3.0       45.0  954594048.0    24
66          300.0         3.0       41.0  954594048.0    25
407         300.0         3.0       37.0  954594048.0    26
124         300.0         3.0       42.0  954594048.0    27
793         700.0         7.0       28.0  954596160.0    28
985         300.0         3.0       28.0  954739648.0    29
415        1500.0         4.0       44.0  954840064.0    30
55          170.0         5.0       45.0  955013696.0    31
326         180.0         5.0       44.0  955053760.0    32
268         180.0         3.0       30.0  955119808.0    33
332         140.0         4.0       40.0  955224384.0    34
430         140.0         4.0       43.0  955224384.0    35
38          140.0         4.0       44.0  955224384.0    36
991         140.0         4.0       33.0  955300928.0    37
57          180.0         3.0       28.0  955346816.0    38
559         240.0         3.0       47.0  955407744.0    39
196        1500.0         6.0       29.0  955431424.0    40
844         120.0         3.0       33.0  955476288.0    41
150         120.0         3.0       34.0  955521344.0    42
886         180.0         5.0       34.0  955571072.0    43
471         700.0         7.0       49.0  955669632.0    44
370         700.0         7.0       47.0  955669632.0    45
789         700.0         7.0       42.0  955669632.0    46
599         700.0         7.0       45.0  955669632.0    47
744        1500.0         3.0       18.0  955782720.0    48
165         700.0         4.0       43.0  955811712.0    49
68          700.0         4.0       45.0  955811712.0    50

In [88]:
# Drop the 'MSE' column from each top_50 DataFrame
top_50_wind_dropped = top_50_wind.drop(columns=['MSE'])
top_50_carbon_dropped = top_50_carbon.drop(columns=['MSE'])
top_50_house_8L_dropped = top_50_house_8L.drop(columns=['MSE'])

# Concatenate the DataFrames
concatenated_df = pd.concat([top_50_wind_dropped, top_50_carbon_dropped, top_50_house_8L_dropped], ignore_index=True)

# Drop repeated rows
concatenated_df = concatenated_df.drop_duplicates()

# Save the concatenated DataFrame to a CSV file
concatenated_df.to_csv('csvs/OOB_plus_IQR_Top_150.csv', index=False)